---
title: Intermedia course R
author: Mette Kathrine nygaard
format: html
---

## Header 1

```{r setup}
#| include: false
library(tidyverse)
library(here)
library(snakecase)
```

```{r}
# Code chunk
```

## Importing CGM data

```{r}
cgm_101 <- here("data-raw/dime/cgm/101.csv") %>%
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )
```

## Exercise: Import 101's sleep data.
```{r}
sleep_101 <- here("data-raw/dime/sleep/101.csv") %>%
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )
```

## Making a function that adds numbers

```{r}
#' Add two numbers together
#'
#' @param num1 A number
#' @param num2 A number
#'
#' @returns Returns the sum of the numbers

add_numbers <- function(num1, num2) {
  added <- num1 + num2
  return(added)
}

add_numbers(1, 2)
```

## Import 101'scgm data with a functin

```{r}
#' Import on participants cgm
#'
#' @param file_path Path to file
#'
#' @returns Returns a data frame
#'
import_cgm <- function(file_path) {
  cgm <- file_path %>%
    read_csv(
      show_col_types = FALSE,
      name_repair = to_snake_case,
      n_max = 100
    )
  return(cgm)
}

here("data-raw/dime/cgm/101.csv") %>%
  import_cgm()

here("data-raw/dime/cgm/102.csv") %>%
  import_cgm()
```
 
## Exercise to make function to import sleep data
 
```{r}
#' Import on participants sleep
#'
#' @param file_path Path to sleep file
#'
#' @returns Returns to a data frame
#'
import_sleep <- function(file_path) {
  sleep <- file_path %>%
    read_csv(
      show_col_types = FALSE,
      name_repair = to_snake_case,
      n_max = 100
    )
  return(sleep)
}

here("data-raw/dime/sleep/101.csv") %>%
  import_sleep()

here("data-raw/dime/sleep/102.csv") %>%
  import_sleep()
```
